name: macos-nightly
on: [push, pull_request]

jobs:
  osx-build:
    name: Testing install script in ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macOS-latest, macos-13 ]

    env:
      GITHUB: true

    steps:
      - uses: actions/checkout@v4
      - name: OS Info
        run: |
          brew install shellcheck
          wget https://raw.githubusercontent.com/dylanaraps/neofetch/master/neofetch && chmod +x ./neofetch && ./neofetch
      - name: Fetch script
        run: |
          curl -OL https://raw.githubusercontent.com/mike325/dotfiles/master/install.sh
          chmod +x ./install.sh
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: nightly
      - name: Install dotfile
        run: |
          ./install.sh --verbose --neovim dotfiles
      - name: Test nightly Neovim
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          make
